"""Portfolio news impact resource definitions."""

from __future__ import annotations

from pathlib import Path

from mcp.server.fastmcp import FastMCP

PORTFOLIO_NEWS_IMPACT_URI = "portfolio://news-impact"


def _cache_file_path() -> Path:
    root = Path(__file__).resolve().parents[2]
    return root / "cache" / "portfolio_news_impact_latest.json"


def _read_cached_news_impact_json() -> str:
    target = _cache_file_path()
    if not target.exists():
        raise ValueError("Portfolio news impact resource not found. Run get_portfolio_news_impact first.")
    payload = target.read_text(encoding="utf-8").strip()
    if not payload:
        raise ValueError("Portfolio news impact resource not found. Run get_portfolio_news_impact first.")
    return payload


def register_portfolio_news_resources(mcp: FastMCP) -> None:
    @mcp.resource(
        PORTFOLIO_NEWS_IMPACT_URI,
        name="portfolio-news-impact",
        title="Portfolio News Impact Cache",
        description="Latest cached JSON result generated by get_portfolio_news_impact.",
        mime_type="application/json",
    )
    def portfolio_news_impact_resource() -> str:
        return _read_cached_news_impact_json()


